# mkdocs.yml
site_name: Mi Portafolio Profesional
site_author: Viviana Prasca Méndez
theme:
  name: material
extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Proyecto de ANN (IA):
      - proyecto-QualityClassifier/QualityClassifier.md
  - Proyecto mobile:
      - proyecto-demeter/demeter.md
